// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9aunZZ4t846y1592QqJ7VC
// Component: FMLuPOlo1F
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 8uJGPonSAj-MG/component
import FooterCreattor from "../../FooterCreattor"; // plasmic-import: --UNrw1048/component

import { useScreenVariants as useScreenVariantsav4KQZoKxu4Muo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: av4kQZoKxu4MUO/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_creattor.module.css"; // plasmic-import: 9aunZZ4t846y1592QqJ7VC/projectcss
import sty from "./PlasmicComoFuncionaCreattor.module.css"; // plasmic-import: FMLuPOlo1F/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: mN1jZXp3Us1XbS/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: nMqfnF4RZnsINk/icon

export type PlasmicComoFuncionaCreattor__VariantMembers = {};

export type PlasmicComoFuncionaCreattor__VariantsArgs = {};
type VariantPropType = keyof PlasmicComoFuncionaCreattor__VariantsArgs;
export const PlasmicComoFuncionaCreattor__VariantProps =
  new Array<VariantPropType>();

export type PlasmicComoFuncionaCreattor__ArgsType = {};
type ArgPropType = keyof PlasmicComoFuncionaCreattor__ArgsType;
export const PlasmicComoFuncionaCreattor__ArgProps = new Array<ArgPropType>();

export type PlasmicComoFuncionaCreattor__OverridesType = {
  root?: p.Flex<"div">;
  p?: p.Flex<"p">;
  footerCreattor?: p.Flex<typeof FooterCreattor>;
};

export interface DefaultComoFuncionaCreattorProps {}

function PlasmicComoFuncionaCreattor__RenderFunc(props: {
  variants: PlasmicComoFuncionaCreattor__VariantsArgs;
  args: PlasmicComoFuncionaCreattor__ArgsType;
  overrides: PlasmicComoFuncionaCreattor__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsav4KQZoKxu4Muo()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__dtWIs)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__wSxFs)}>
                <div className={classNames(projectcss.all, sty.column__qHcUu)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jdfqb)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__axqui
                      )}
                    >
                      {"Como funciona?"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__otvje
                      )}
                    >
                      {
                        "Com o creattor, todos ganham. Marcas, influenciadores e nossa comunidade "
                      }
                    </div>

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button___805Cf
                        )}
                        color={"darkBlue" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("#contato" as const)
                            : undefined
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vnaay
                          )}
                        >
                          {"Saiba mais"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column___31Nn)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7W6Mv)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gwIfD)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/image851Png.png",
                          fullWidth: 259,
                          fullHeight: 335,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <p
                        data-plasmic-name={"p"}
                        data-plasmic-override={overrides.p}
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p
                        )}
                      >
                        {"Estamos aqui! Estamos prontos para te atender."}
                      </p>
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__xpBk5
                        )}
                        color={"darkBlue" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                            : ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eDlsY
                          )}
                        >
                          {"ENTRE EM CONTATO"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <section className={classNames(projectcss.all, sty.section__vTnje)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__iKmjU
              )}
            >
              {"Últimas avaliações"}
            </h2>

            <div className={classNames(projectcss.all, sty.freeBox__coyDp)}>
              <div className={classNames(projectcss.all, sty.freeBox__bUnEs)}>
                <div className={classNames(projectcss.all, sty.columns__oT6T)}>
                  <div
                    className={classNames(projectcss.all, sty.column___2YvW0)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wJtFv)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__vfP7T)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/image74Png.png",
                          fullWidth: 118,
                          fullHeight: 118,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__voo8Y
                        )}
                      >
                        {"@alexia.kronig"}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__xG5C2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bmGgr)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__eulRy)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/image74Png.png",
                          fullWidth: 118,
                          fullHeight: 118,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gnYzq
                        )}
                      >
                        {"@alexia.kronig"}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___4A3Bs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__liVQu)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__pn0Zk)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/image74Png.png",
                          fullWidth: 118,
                          fullHeight: 118,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iJfK
                        )}
                      >
                        {"@alexia.kronig"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__mr93D)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__gl2F)}>
                <div className={classNames(projectcss.all, sty.column__hHGl8)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sjh9T)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__qen2G
                      )}
                    >
                      {"O que as marcas ganham?"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uYYrB
                      )}
                    >
                      {
                        "Conteúdo social que gera mais valor e engamento nas redes sociais"
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fHmlT)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__tVinu)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r5Ev8
                        )}
                      >
                        {"Aumento na taxa de conversão"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__svqGb
                        )}
                      >
                        {
                          "Reconhecimento social é o item que mais traz segurança para o consumidor na hora da compra"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wuOsa
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5VOTb
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nqzxC
                        )}
                      >
                        {"Vídeos\nde Produtos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k0CYc
                        )}
                      >
                        {
                          "Sem altos custos de produção. \nCom o creattor ganham escala e credibilidade nos videos"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lKh0
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__x8BEs)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i9OQ
                        )}
                      >
                        {"Engajamento\nSocial"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iqxuN
                        )}
                      >
                        {
                          "Comentários, likes e shares de sua marca e produtos, quanto mais videos mais engajamento"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hkTej
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__pCkXc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tSeam
                        )}
                      >
                        {"Aumento \nde seguidores"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__k7OCp
                        )}
                      >
                        {
                          "Quanto mais os creattors divulgam sua marca mais seguidores você ganha "
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zcxH
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__sspmM)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns___81CAa)}>
                <div className={classNames(projectcss.all, sty.column__z9PI)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pLbT9)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__eEvEg
                      )}
                    >
                      {"O que as creattors ganham?"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8YXk
                      )}
                    >
                      {
                        "Cashback ao avaliar compras com oportunidade de monetizar conteúdo e virar um creattor profissional"
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__a4Xgh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__un6Da)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__mSeyS
                        )}
                      >
                        {"Receita mensal sem sair de casa"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oulfV
                        )}
                      >
                        {
                          "Quanto mais videos publicados, mais ganhos. Clique aqui e veja os exemplos de remuneração"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__x8Mjn
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__cbCRr)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fx6RJ
                        )}
                      >
                        {"Reconhecimento social"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3R3T9
                        )}
                      >
                        {
                          "Quanto mais relevante o creattor fica, mais chances de virar um influenciador e criar para marcas"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__m5Fpr
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__shFsi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nPM
                        )}
                      >
                        {"Quanto um creattor ganha?"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dcjch
                        )}
                      >
                        {
                          "Cashback, dinheiro em conta e cupons de desconto. Clique aqui e veja exemplos dos ganhos"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__smU5O
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__dWgN2)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__vwreD)}>
                <div className={classNames(projectcss.all, sty.column__mm4NF)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__b5IW2)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__lijB2
                      )}
                    >
                      {"Quantos os creattors ganham?"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5OtM
                      )}
                    >
                      {
                        "Veja quanto você pode ganhar compartilhando em cada uma das redes"
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__i3EAb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___2Bqns
                      )}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__op9V3)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/group11Png.png",
                          fullWidth: 48,
                          fullHeight: 48,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hKhKg
                        )}
                      >
                        {"Tabela completa de ganhos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__guR2V
                        )}
                      >
                        {
                          "Clique aqui e veja quanto você pode ganhar em cada uma das redes"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i09F
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__zhutr)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__syLpO)}>
                <div className={classNames(projectcss.all, sty.column__hohBx)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mXvs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wmTvb
                      )}
                    >
                      {"Exemplo de moetização do creattor"}
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__y8Ec1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__n9FHc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qmXnc
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__uN08)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/group11Png.png",
                            fullWidth: 48,
                            fullHeight: 48,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__pnQT
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cBPnA
                            )}
                          >
                            {"Total"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ilPnM
                            )}
                          >
                            {"YT + Insta + FB + Tiktok + Review"}
                          </div>
                        </div>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__p7Fi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column___8Obxg
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__syhoh
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__aTha8
                              )}
                            >
                              {"cashback"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jUNm
                              )}
                            >
                              {"45%"}
                            </div>
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__diCeE
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__oanMe
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yvt9P
                              )}
                            >
                              {"cashback"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__n2UPx
                              )}
                            >
                              {"45%"}
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__fb08H)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__tlaP6)}>
                <div className={classNames(projectcss.all, sty.column___6JV0L)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___8O84E)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__t7Qna
                      )}
                    >
                      {"O que os consumidores ganham?"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rl9V
                      )}
                    >
                      {
                        "Avaliações reais de produtos feitas por nossa comunidade de creattors, criadores de conteúdos profissionais e influenciadores"
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__w6Tw9)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qZjeW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pov7F
                        )}
                      >
                        {"Segurança para comprar produtos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6WLSu
                        )}
                      >
                        {
                          "Sem surpresas de qualidade, prazos de entrega e devolução na hora da compra"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pW087
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__bet8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rEpup
                        )}
                      >
                        {"Conhecer antes de comprar"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bpSLw
                        )}
                      >
                        {
                          "Os videos dos creattor ajudam a conhecer os produtos, reduzindo  duvidas na hora da compra"
                        }
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__g0Bjk
                        )}
                      >
                        {"Veja mais "}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <FooterCreattor
            data-plasmic-name={"footerCreattor"}
            data-plasmic-override={overrides.footerCreattor}
            className={classNames("__wab_instance", sty.footerCreattor)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "p", "footerCreattor"],
  p: ["p"],
  footerCreattor: ["footerCreattor"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  p: "p";
  footerCreattor: typeof FooterCreattor;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicComoFuncionaCreattor__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicComoFuncionaCreattor__VariantsArgs;
    args?: PlasmicComoFuncionaCreattor__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicComoFuncionaCreattor__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicComoFuncionaCreattor__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicComoFuncionaCreattor__ArgProps,
          internalVariantPropNames: PlasmicComoFuncionaCreattor__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicComoFuncionaCreattor__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComoFuncionaCreattor";
  } else {
    func.displayName = `PlasmicComoFuncionaCreattor.${nodeName}`;
  }
  return func;
}

export const PlasmicComoFuncionaCreattor = Object.assign(
  // Top-level PlasmicComoFuncionaCreattor renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    p: makeNodeComponent("p"),
    footerCreattor: makeNodeComponent("footerCreattor"),

    // Metadata about props expected for PlasmicComoFuncionaCreattor
    internalVariantProps: PlasmicComoFuncionaCreattor__VariantProps,
    internalArgProps: PlasmicComoFuncionaCreattor__ArgProps
  }
);

export default PlasmicComoFuncionaCreattor;
/* prettier-ignore-end */
