// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9aunZZ4t846y1592QqJ7VC
// Component: lEqnajZCdK
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 8uJGPonSAj-MG/component

import { useScreenVariants as useScreenVariantsav4KQZoKxu4Muo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: av4kQZoKxu4MUO/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_creattor.module.css"; // plasmic-import: 9aunZZ4t846y1592QqJ7VC/projectcss
import sty from "./PlasmicHomeCreattor.module.css"; // plasmic-import: lEqnajZCdK/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: mN1jZXp3Us1XbS/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: nMqfnF4RZnsINk/icon

export type PlasmicHomeCreattor__VariantMembers = {};

export type PlasmicHomeCreattor__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomeCreattor__VariantsArgs;
export const PlasmicHomeCreattor__VariantProps = new Array<VariantPropType>();

export type PlasmicHomeCreattor__ArgsType = {};
type ArgPropType = keyof PlasmicHomeCreattor__ArgsType;
export const PlasmicHomeCreattor__ArgProps = new Array<ArgPropType>();

export type PlasmicHomeCreattor__OverridesType = {
  root?: p.Flex<"div">;
  footer?: p.Flex<"footer">;
};

export interface DefaultHomeCreattorProps {}

function PlasmicHomeCreattor__RenderFunc(props: {
  variants: PlasmicHomeCreattor__VariantsArgs;
  args: PlasmicHomeCreattor__ArgsType;
  overrides: PlasmicHomeCreattor__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsav4KQZoKxu4Muo()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__fGaE3)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__kbHpf)}>
                <div className={classNames(projectcss.all, sty.column__a8BMa)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aRJos)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__fHfoA
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Crie vídeos, avalie suas compras \ne "}
                        </React.Fragment>
                        {
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span___5DlZv
                            )}
                          >
                            {"ganhe cashback"}
                          </span>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uoGZv
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Compartilhe suas avaliações nas redes sociais e "}
                        </React.Fragment>
                        {
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__cOxI5
                            )}
                          >
                            {"ganhe cashback"}
                          </span>
                        }
                        <React.Fragment>{" em suas compras"}</React.Fragment>
                      </React.Fragment>
                    </div>

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__kWeFe
                        )}
                        color={"softPink" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("#contato" as const)
                            : undefined
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___87Qh5
                          )}
                        >
                          {"Criar conta"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__dv6T1)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__aUbTv)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jiTY)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"391px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/group8Png.png",
                          fullWidth: 393,
                          fullHeight: 469,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <p
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p__vCGxj
                        )}
                      >
                        {"Estamos aqui! Estamos prontos para te atender."}
                      </p>
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ltEb
                        )}
                        color={"darkBlue" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                            : ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uvFCd
                          )}
                        >
                          {"ENTRE EM CONTATO"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <section className={classNames(projectcss.all, sty.section__dzdJe)}>
            <div className={classNames(projectcss.all, sty.freeBox__kKUe)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__diyWs
                )}
              >
                {"Últimas avaliações"}
              </h2>

              <div className={classNames(projectcss.all, sty.freeBox__bdoP)}>
                <div className={classNames(projectcss.all, sty.freeBox__ycYgS)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__flcDn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__yWIg4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fJlqG
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__oGfYx)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image74Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fpbwk
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__qIGx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0O7A9
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__d2OXc)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image393Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sEaw5
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__n5F6N)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jWEvv
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xzY86)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image73Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6HC2Z
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column___9JlDk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dO6EC
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___3Onp7)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image29Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hntmD
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__qqz31)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pALbh
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__aqzYi)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image291Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__l16BY
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__i6B5S)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__efvRv
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__rHqGk)}
                          displayHeight={"auto" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/creattor/images/image292Png.png",
                            fullWidth: 118,
                            fullHeight: 118,
                            aspectRatio: undefined
                          }}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bssKy
                          )}
                        >
                          {"@alexia.kronig"}
                        </div>
                      </div>
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__pUvCj)}>
            <div className={classNames(projectcss.all, sty.freeBox__hhfZt)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__kd7Hs
                )}
              >
                <React.Fragment>
                  <React.Fragment>{"Comece a "}</React.Fragment>
                  {
                    <span
                      className={classNames(
                        projectcss.all,
                        projectcss.span,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.span__q469
                      )}
                    >
                      {"ganhar"}
                    </span>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </h2>

              <div className={classNames(projectcss.all, sty.columns__oZyTi)}>
                <div className={classNames(projectcss.all, sty.column___419Rc)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yjFyL)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l5EMn
                      )}
                    >
                      {"Compre um produto"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rB7Bk
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"De uma de nossas "}</React.Fragment>
                        {
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__tWlff
                            )}
                          >
                            {"lojas on-line parceiras"}
                          </span>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__kkHtq)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"356px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group41Png.png",
                        fullWidth: 842,
                        fullHeight: 777,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__r6ATh
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/" as const}
                    platform={"nextjs"}
                  >
                    {"Ver todas as lojas parceiras"}
                  </p.PlasmicLink>
                </div>

                <div className={classNames(projectcss.all, sty.column__bWVl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yQq9D)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qJ8N9
                      )}
                    >
                      {"Faça uma avaliação \nem vídeo"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sTqeu
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Use a "}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"criatividade"}
                        </span>
                        <React.Fragment>
                          {" e grave um vídeo com sua "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"opinião "}
                        </span>
                        <React.Fragment>
                          {"sobre o produto que comprou"}
                        </React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__t8BJu)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"356px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group39Png.png",
                        fullWidth: 344,
                        fullHeight: 324,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___1Ked3
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/" as const}
                    platform={"nextjs"}
                  >
                    {"Dicas para gravar seus vídeos"}
                  </p.PlasmicLink>
                </div>

                <div className={classNames(projectcss.all, sty.column__wff04)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__v0Zu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kobCo
                      )}
                    >
                      {"Envie pra gente \ne comece a ganhar"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bUsyi
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"Se o seu vídeo for aprovado, você recebe "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"cashback em dinheiro"}
                        </span>
                        <React.Fragment>
                          {" direto na sua conta"}
                        </React.Fragment>
                      </React.Fragment>
                    </div>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__biRi4)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"356px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group41Png.png",
                        fullWidth: 842,
                        fullHeight: 777,
                        aspectRatio: undefined
                      }}
                    />
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__a14Nv
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/" as const}
                    platform={"nextjs"}
                  >
                    {"Veja quanto você pode ganhar"}
                  </p.PlasmicLink>
                </div>
              </div>
            </div>
          </section>

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__rMs2U)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__dcaWc)}>
                <div className={classNames(projectcss.all, sty.column__bcn12)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lLJ0)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__fd3SP)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/group50701Png.png",
                          fullWidth: 407,
                          fullHeight: 574,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <p
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p___9VjiA
                        )}
                      >
                        {"Estamos aqui! Estamos prontos para te atender."}
                      </p>
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__yh25X
                        )}
                        color={"darkBlue" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                            : ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__al21P
                          )}
                        >
                          {"ENTRE EM CONTATO"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__dh7B)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__uxq8I)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__qhea8
                      )}
                    >
                      {"Compartilhe o vídeo em suas redes e ganhe ainda mais"}
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fXn7N
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "Quanto maior o número de curtidas, comentários, visualizações e compartilhamentos "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"mais cashback você ganha"}
                        </span>
                      </React.Fragment>
                    </div>

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__bg85E
                        )}
                        color={"creattorColor" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("#contato" as const)
                            : undefined
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xMn9B
                          )}
                        >
                          {"Como funciona?"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__oFNmJ)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__o0Pk)}>
                <div className={classNames(projectcss.all, sty.column__ysVod)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zrkLi)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__wegiq
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Você já cria "}</React.Fragment>
                        {
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__fwLgq
                            )}
                          >
                            {"conteúdo "}
                          </span>
                        }
                        <React.Fragment>{"profissionalmente?"}</React.Fragment>
                      </React.Fragment>
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kthUk
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "Crie sua conta e faça parte da nossa comunidade de criadores, "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"gerando renda e engajamento"}
                        </span>
                        <React.Fragment>
                          {" para nossas marcas parceiras"}
                        </React.Fragment>
                      </React.Fragment>
                    </div>

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__bqSk
                        )}
                        color={"creattorColor" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("#contato" as const)
                            : undefined
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___05XQo
                          )}
                        >
                          {"Cadastre-se"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.column__wmgtW)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yqDXl)}
                  >
                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ato54)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"314px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/group50649Png.png",
                          fullWidth: 285,
                          fullHeight: 493,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}

                    {true ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iGpnj)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"314px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/creattor/images/group506891Png.png",
                          fullWidth: 285,
                          fullHeight: 493,
                          aspectRatio: undefined
                        }}
                      />
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <p
                        className={classNames(
                          projectcss.all,
                          projectcss.p,
                          projectcss.__wab_text,
                          sty.p__c7NiN
                        )}
                      >
                        {"Estamos aqui! Estamos prontos para te atender."}
                      </p>
                    ) : null}

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__bhLiA
                        )}
                        color={"darkBlue" as const}
                        link={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                            : ("https://api.whatsapp.com/send?phone=5513920001845&text=Ol%C3%A1!" as const)
                        }
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o7XJe
                          )}
                        >
                          {"ENTRE EM CONTATO"}
                        </div>
                      </Button>
                    ) : null}
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__cnJL)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__pZkBz)}>
                <div className={classNames(projectcss.all, sty.column___3EM0C)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ybPcn)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__sgCS
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{"Nossas "}</React.Fragment>
                        {
                          <span
                            className={classNames(
                              projectcss.all,
                              projectcss.span,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.span__lZnXb
                            )}
                          >
                            {"creattors"}
                          </span>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </h2>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__peFp4
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "Somos influenciadores, personalidades e investidores criando conteúdo para marcas e recompensando nossa comunidade de criadores com "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"vantagens e cashbacks."}
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <section className={classNames(projectcss.all, sty.section__qc2Fs)}>
            <div className={classNames(projectcss.all, sty.freeBox__bRtUl)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__jnTd6)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/image64Png.png",
                  fullWidth: 279,
                  fullHeight: 433,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mw7Kd
                )}
              >
                {"Sabrina Sato"}
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__vaH6T)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___7CT9B)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/image601Png.png",
                  fullWidth: 279,
                  fullHeight: 433,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pg4Tj
                )}
              >
                {"Boca Rosa"}
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__l90Pb)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dHq3P)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/image64Png.png",
                  fullWidth: 279,
                  fullHeight: 433,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cgZPs
                )}
              >
                {"Sabrina Sato"}
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__zalLq)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__hc8NP)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/image601Png.png",
                  fullWidth: 279,
                  fullHeight: 433,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y4NpH
                )}
              >
                {"Boca Rosa"}
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__aRxUe)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__xObkW)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/image64Png.png",
                  fullWidth: 279,
                  fullHeight: 433,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__m91Wq
                )}
              >
                {"Sabrina Sato"}
              </div>
            </div>
          </section>

          {true ? (
            <section
              className={classNames(projectcss.all, sty.section__lg4AP)}
              id={"sobre" as const}
            >
              <div className={classNames(projectcss.all, sty.columns__bFgJx)}>
                <div className={classNames(projectcss.all, sty.column___4Ab7J)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__o6MUy)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__wC05L
                      )}
                    >
                      {"Comunidade creattor"}
                    </h2>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kHvhW)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__oWBfQ)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group58Png.png",
                        fullWidth: 281,
                        fullHeight: 234,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__snaOz)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group58Png.png",
                        fullWidth: 281,
                        fullHeight: 234,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ovhRm)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group58Png.png",
                        fullWidth: 281,
                        fullHeight: 234,
                        aspectRatio: undefined
                      }}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iybTe)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"auto" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/creattor/images/group58Png.png",
                        fullWidth: 281,
                        fullHeight: 234,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </section>
          ) : null}

          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__s4Jw)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4TAwl
                )}
              >
                {"Na mídia"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__i5RQp
                )}
              >
                {"Veja o que estão falando da gente"}
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__ppusX)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__tKlsZ)}
                  displayHeight={"26px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"130px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/image701Png.png",
                    fullWidth: 130,
                    fullHeight: 26,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dfr45)}
                  displayHeight={"21px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"139px" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/image711Png.png",
                    fullWidth: 139,
                    fullHeight: 21,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__a4Ev)}
                  displayHeight={"21px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"127px" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/path6881Png.png",
                    fullWidth: 127,
                    fullHeight: 21,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5INB)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/image721Png.png",
                    fullWidth: 49,
                    fullHeight: 52,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__ppemf)}
                  displayHeight={"36px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/group50641Png.png",
                    fullWidth: 36,
                    fullHeight: 36,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__a6Nr)}
                  displayHeight={"36px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/group50642Png.png",
                    fullWidth: 36,
                    fullHeight: 36,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___3RE8D)}
                  displayHeight={"36px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/creattor/images/group50643Png.png",
                    fullWidth: 36,
                    fullHeight: 36,
                    aspectRatio: undefined
                  }}
                />
              </div>

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rfPcW)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"auto" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/creattor/images/group50646Png.png",
                  fullWidth: 113,
                  fullHeight: 41,
                  aspectRatio: undefined
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mPEoc
                )}
              >
                {"© 2022 Creattor.io. All rights reserved."}
              </div>
            </div>
          </footer>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "footer"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomeCreattor__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomeCreattor__VariantsArgs;
    args?: PlasmicHomeCreattor__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomeCreattor__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomeCreattor__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomeCreattor__ArgProps,
          internalVariantPropNames: PlasmicHomeCreattor__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomeCreattor__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeCreattor";
  } else {
    func.displayName = `PlasmicHomeCreattor.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeCreattor = Object.assign(
  // Top-level PlasmicHomeCreattor renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomeCreattor
    internalVariantProps: PlasmicHomeCreattor__VariantProps,
    internalArgProps: PlasmicHomeCreattor__ArgProps
  }
);

export default PlasmicHomeCreattor;
/* prettier-ignore-end */
