// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9aunZZ4t846y1592QqJ7VC
// Component: vaj-9rOxoU0Ehi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_creattor.module.css"; // plasmic-import: 9aunZZ4t846y1592QqJ7VC/projectcss
import sty from "./PlasmicSimpleTextarea.module.css"; // plasmic-import: vaj-9rOxoU0Ehi/css

export type PlasmicSimpleTextarea__VariantMembers = {};

export type PlasmicSimpleTextarea__VariantsArgs = {};
type VariantPropType = keyof PlasmicSimpleTextarea__VariantsArgs;
export const PlasmicSimpleTextarea__VariantProps = new Array<VariantPropType>();

export type PlasmicSimpleTextarea__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicSimpleTextarea__ArgsType;
export const PlasmicSimpleTextarea__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicSimpleTextarea__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  label?: p.Flex<"label">;
  textarea?: p.Flex<"textarea">;
};

export interface DefaultSimpleTextareaProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicSimpleTextarea__RenderFunc(props: {
  variants: PlasmicSimpleTextarea__VariantsArgs;
  args: PlasmicSimpleTextarea__ArgsType;
  overrides: PlasmicSimpleTextarea__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <label
          data-plasmic-name={"label"}
          data-plasmic-override={overrides.label}
          className={classNames(projectcss.all, sty.label)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Label",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </label>

        <textarea
          data-plasmic-name={"textarea"}
          data-plasmic-override={overrides.textarea}
          className={classNames(
            projectcss.all,
            projectcss.textarea,
            sty.textarea
          )}
          rows={4 as const}
          value={"" as const}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "label", "textarea"],
  freeBox: ["freeBox", "label", "textarea"],
  label: ["label"],
  textarea: ["textarea"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  label: "label";
  textarea: "textarea";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSimpleTextarea__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSimpleTextarea__VariantsArgs;
    args?: PlasmicSimpleTextarea__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSimpleTextarea__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSimpleTextarea__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSimpleTextarea__ArgProps,
          internalVariantPropNames: PlasmicSimpleTextarea__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSimpleTextarea__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSimpleTextarea";
  } else {
    func.displayName = `PlasmicSimpleTextarea.${nodeName}`;
  }
  return func;
}

export const PlasmicSimpleTextarea = Object.assign(
  // Top-level PlasmicSimpleTextarea renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    label: makeNodeComponent("label"),
    textarea: makeNodeComponent("textarea"),

    // Metadata about props expected for PlasmicSimpleTextarea
    internalVariantProps: PlasmicSimpleTextarea__VariantProps,
    internalArgProps: PlasmicSimpleTextarea__ArgProps
  }
);

export default PlasmicSimpleTextarea;
/* prettier-ignore-end */
